### ISSUE TITLE
How does it deal with atomic updates on /etc/hosts file?

### ISSUE THREAD

**Issue by manishtradebyte** [sous-chefs/line-cookbook#260]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

replace_or_add when used on /etc/hosts file gives  Errno::EBUSY
           ------------
           Device or resource busy @ rb_file_s_rename - (/etc/.chef-hosts20231116-133-1ndi0k, /etc/hosts)

## :pancakes: Cookbook version

Version of the cookbook where you are encountering the issue.

## :woman_cook:  Chef-Infra Version

Version of chef-client in your environment.

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by MarkGibbons** [comment]
If you are trying to configure /etc/hosts in a docker container there are some docker specific restrictions.

Otherwise could you fill in the platform details, the chef version info, and include the code that uses the replace_or_add resource?

Replace_or_add is using the chef file resource to replace the updated file so most likely the cause of problems is going to be in how the file resource is implemented or used.  Chef has specific and different features implemented for managing /etc/hosts in docker containers.

**Comment by manishtradebyte** [comment]
I am using it in docker. The chefdk version id 3.12.10
I know that docker imposes restrictions on etc/hosts file that it can be renamed, hence the atomic updates are failing. There is a option to disable atomic update in file resource can you provide something similar in  Replace_or_add?

**Comment by MarkGibbons** [comment]
Something is not making sense.  From the documentation for the file resource.

_atomic_update
Ruby Type: true, false | Default Value: false if modifying /etc/hosts, /etc/hostname, or /etc/resolv.conf within Docker containers. Otherwise default to the client.rb 'file_atomic_update' config value.
Perform atomic file updates on a per-resource basis.

Set to true for atomic file updates. Set to false for non-atomic file updates.

This setting overrides file_atomic_update, which is a global setting found in the client.rb file._


Updates to /etc/hosts should already set atomic_update to false.  Could you try doing the update with file_atomic_update false in client.rb to see if that makes any difference?

**Comment by manishtradebyte** [comment]
Could you try doing the update with file_atomic_update false in client.rb to see if that makes any difference?
-- This works but then i dont want to disable atomic-updates on all resources.

**Comment by MarkGibbons** [comment]
That test makes it look like the file resource is not working as documented.   I'll see if I can reproduce the failure in dokken.  You might see if chef/progress would look at a trouble ticket for the issue.

**Comment by MarkGibbons** [comment]
What version of the chef client are you using?  You gave me the version of chefdk.  chefdk was replaced quite a while ago as software ages.  You may just have too old of a version of the client.

When I run an update against /etc/hosts in a container it works for me. see the containerHosts pull request in this project.

**Comment by manishtradebyte** [comment]
I am using chef-client  14.14.29
I gave up on the idea of using docker image and i am using aws ami instead . The code works there without any issues in aws ami.

**Comment by MarkGibbons** [comment]
That version of the client might just be old enough to pick up a version of the file resource before the fix for /etc/hosts in docker images.  Good luck.
